name: Generate terraform READme
on:
  workflow_dispatch: 
  push:
    tags: 
      - v*.*.*
jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: main

        - name: Generate TF Docs
          uses: terraform-docs/gh-actions@v1.3.0
          with:
            working-dir: .
            output-file: README.md
            output-method: inject
            # recursive: true
            # recursive-path: modules
            git-push: true
